/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-24 06:02:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lec_005fscript_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Insert title here</title>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Javascript 테스트 -->\r\n");
      out.write("	<script src=\"js/my.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("	   //public int myprint(int a, int b) {  syso.print... }\r\n");
      out.write("	   function myprint(a, b) {\r\n");
      out.write("		   //alert(a+b);\r\n");
      out.write("		   console.log(a+b);\r\n");
      out.write("	   }\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- CSS 테스트 -->\r\n");
      out.write("	<style>\r\n");
      out.write("	  	p {\r\n");
      out.write("	    	color:red;\r\n");
      out.write("	    	font-weight:bold;\r\n");
      out.write("	  	}\r\n");
      out.write("    </style>\r\n");
      out.write("  	<link href=\"css/my.css\" rel=\"stylesheet\" />\r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("  	<!-- JQuery 테스트  ------------------------------------\r\n");
      out.write("  	$  (document).ready    (        function() {}     );\r\n");
      out.write("	$                      (        function() {}     );\r\n");
      out.write("  	\r\n");
      out.write("  	id    = \"abc\"    $(\"#abc\")\r\n");
      out.write("  	class = \"abc\"    $(\".abc\")\r\n");
      out.write("  	-->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("		$(function() {\r\n");
      out.write("		  	//$(\"p\").text(  \"text 변경변경\"  );\r\n");
      out.write("			$(\"#PTAG_ID\").text(  \"text 변경변경-#PTAG_ID\"  );\r\n");
      out.write("			\r\n");
      out.write("			$(\".PTAG_CLASS\").text(  \"text 변경변경-.PTAG_CLASS\"  );\r\n");
      out.write("			//$(\"#PTAG_ID_11\").text(  \"text 변경변경-.PTAG_CLASS\"  );\r\n");
      out.write("			//$(\"#PTAG_ID_22\").text(  \"text 변경변경-.PTAG_CLASS\"  );\r\n");
      out.write("			\r\n");
      out.write("			//---------------------------------------------------------\r\n");
      out.write("			//uname에 값 넣기     == value=\"hong\"\r\n");
      out.write("			//---------------------------------------------------------\r\n");
      out.write("			// $(\"#uname\").val(\"hong\");                //id로 접근\r\n");
      out.write("			// $(\".uname\").val(\"hong\");                //class로 접근\r\n");
      out.write("			// $(\"input[name='uname']\").val(\"hong\");   //name으로 접근\r\n");
      out.write("			$(\"#uname\").val(\"hong\"); \r\n");
      out.write("			\r\n");
      out.write("			//var msg = $(\"#seq\").val();  //seq     값 가져오기\r\n");
      out.write("			//alert(  msg );  \r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			$(\"#regbtn\").click(  function(){\r\n");
      out.write("				if ($(\"#uname\").val() == \"\") {\r\n");
      out.write("					alert(\"아이디 입력하세요\");\r\n");
      out.write("					$(\"#uname\").focus();\r\n");
      out.write("					return false;\r\n");
      out.write("				} else if ($(\"#passwd\").val() == \"\") {\r\n");
      out.write("					alert(\"비번 입력하세요\");\r\n");
      out.write("					$(\"#passwd\").focus();\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				$(\"#loginForm\").attr(\"method\",\"post\");\r\n");
      out.write("				$(\"#loginForm\").attr(\"action\",\"/BoardServlet\");\r\n");
      out.write("				$(\"#loginForm\").submit();\r\n");
      out.write("				return true;\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   <form name=\"loginForm\" id=\"loginForm\" method=\"post\">  method action <br>\r\n");
      out.write("    	hidden:<input type=\"hidden\"    name=\"seq\"    id=\"seq\"    class=\"seq\"    value=\"12345\"><br>\r\n");
      out.write("    	uname:<input type=\"text\"      name=\"uname\"  id=\"uname\"  class=\"uname\"><br>\r\n");
      out.write("    	passwd:<input type=\"password\"  name=\"passwd\" id=\"passwd\" class=\"passwd\"><br>\r\n");
      out.write("    	<input type=\"button\"    name=\"regbtn\" id=\"regbtn\" class=\"regbtn\"  value=\"가입\">\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("	<p id=\"PTAG_ID\">Not loaded yet111</p>  <!--  id : 고유해야 한다. -->\r\n");
      out.write("	\r\n");
      out.write("	<br>\r\n");
      out.write("	\r\n");
      out.write("	<p id=\"PTAG_ID_11\" class=\"PTAG_CLASS\">aaaaa</p>		   <!--  class : 일괄 적용시켜야 할 경우 사용 -->\r\n");
      out.write("	<p id=\"PTAG_ID_22\" class=\"PTAG_CLASS\">bbbbb</p>\r\n");
      out.write("	\r\n");
      out.write(" 	<!-- Java 호출\r\n");
      out.write(" 	import webapp.js.all\r\n");
      out.write(" 	lec_script ls = new lec_script();\r\n");
      out.write(" 	ls.myprint(5,3);\r\n");
      out.write(" 	\r\n");
      out.write(" 	-->\r\n");
      out.write(" 	<!-- JavaScript 호출 \r\n");
      out.write(" 	<script src=\"webapp/    js/scripts.js\"></script>\r\n");
      out.write(" 	<script src=\"js/scripts.js\"></script>\r\n");
      out.write(" 	\r\n");
      out.write(" 	document.getElementByName(\"loginForm\")\r\n");
      out.write(" 	-->\r\n");
      out.write("    <a href=\"#\" onClick=\"myprint(5,3)\">내부 js 클릭</a><br>\r\n");
      out.write("    <div onClick=\"myprint(5,3)\"> 내부 js div 클릭  </div>\r\n");
      out.write("    <a href=\"#\" onClick=\"myjsPrint()\">외부 my.js 클릭</a><br>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- \r\n");
      out.write("    jQuery는 HTML의 클라이언트 사이드 조작을 (단순화) 하도록 설계된 \r\n");
      out.write("            크로스 플랫폼의 (자바스크립트 라이브러리)다\r\n");
      out.write("     - <form> 제어        \r\n");
      out.write("     - 조건문(if)\r\n");
      out.write("     - 반복문(for , foreach)\r\n");
      out.write("     - 전송 (Ajax)\r\n");
      out.write("     -->\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
