/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-28 03:58:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lec_005fscript2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var arr = [{\"empno\":\"7733\", \"ename\":\"smith\"} , \r\n");
      out.write("    {\"empno\":\"7799\", \"ename\":\"king\"}];\r\n");
      out.write("    \r\n");
      out.write("for(var i = 0; i<arr.length;i++){\r\n");
      out.write("	console.log(arr[i][\"empno\"]);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var arr2 = [[\"7733\", \"smith\"], [\"7799\", \"king\"]];\r\n");
      out.write("\r\n");
      out.write("for(var i = 0; i<arr2.length;i++){\r\n");
      out.write("	console.log(arr2[i][0]);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var arr3 = [[\"7733\", \"smith\"], [\"7799\", \"king\"]];\r\n");
      out.write("\r\n");
      out.write("arr3.forEach(function(val, idx){\r\n");
      out.write("	console.log(val[1]);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		myprint(\"홍길동\");\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		var arr4 = [[\"7733\", \"smith\"], [\"7799\", \"king\"]];\r\n");
      out.write("		//여기는 인덱스 먼저임 주의하셈\r\n");
      out.write("		$.each(arr4, function(idx, val){ \r\n");
      out.write("			console.log(val[1]);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		var arr5 = [{\"empno\":\"7733\", \"ename\":\"smith\"} , \r\n");
      out.write("		    {\"empno\":\"7799\", \"ename\":\"king\"}];\r\n");
      out.write("		$.map(arr5, function(val, idx){\r\n");
      out.write("			console.log(val[\"ename\"]);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#myBtn\").click(  function(){\r\n");
      out.write("			myprint2(\"호출요\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#myDiv\").click(  function(){\r\n");
      out.write("			myprint2(\"호출요\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("function myprint(prm){\r\n");
      out.write("	console.log(\"myprint()호출 \" + prm);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function myprint2(prm){\r\n");
      out.write("	confirm(\"myprint()호출 \" + prm);\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("스크립트 반복문 연습\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\" onClick=\"myprint2('test');\">스크립트 호출</a>\r\n");
      out.write("<table border=1 width=100><tr><td style=\"cursor:pointer\" onClick=\"myprint2('test');\">스크립트 호출</td></tr></table>\r\n");
      out.write("<input type=\"button\" id=\"myBtn\" value=\"버튼 클릭\">\r\n");
      out.write("<div id=\"myDiv\">div클릭</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
