/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-05-22 03:29:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"author\" content=\"\" />\r\n");
      out.write("<title>Register - SB Admin</title>\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v6.3.0/js/all.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-primary\">\r\n");
      out.write("	<div id=\"layoutAuthentication\">\r\n");
      out.write("		<div id=\"layoutAuthentication_content\">\r\n");
      out.write("			<main>\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row justify-content-center\">\r\n");
      out.write("						<div class=\"col-lg-7\">\r\n");
      out.write("							<div class=\"card shadow-lg border-0 rounded-lg mt-5\">\r\n");
      out.write("								<div class=\"card-header\">\r\n");
      out.write("									<h3 class=\"text-center font-weight-light my-4\">Create\r\n");
      out.write("										Account</h3>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<form method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/UserServlet\">\r\n");
      out.write("									<input type = \"hidden\" name=\"pagecode\" value=\"P001\"> \r\n");
      out.write("										<div class=\"row mb-3\">\r\n");
      out.write("											<div class=\"col-md-6\">\r\n");
      out.write("												<div class=\"form-floating mb-3 mb-md-0\">\r\n");
      out.write("													<input name=\"userid\" class=\"form-control\" id=\"inputUserid\"\r\n");
      out.write("														type=\"text\" placeholder=\"Enter your ID\" /> <label\r\n");
      out.write("														for=\"inputFirstName\">ID</label>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-md-6\">\r\n");
      out.write("												<div class=\"form-floating\">\r\n");
      out.write("													<input name=\"uname\" class=\"form-control\" id=\"inputName\"\r\n");
      out.write("														type=\"text\" placeholder=\"Enter your last name\" /> <label\r\n");
      out.write("														for=\"inputLastName\">Name</label>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"form-floating mb-3\">\r\n");
      out.write("											<input name=\"email\" class=\"form-control\" id=\"inputEmail\"\r\n");
      out.write("												type=\"email\" placeholder=\"name@example.com\" /> <label\r\n");
      out.write("												for=\"inputEmail\">Email address</label>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"row mb-3\">\r\n");
      out.write("											<div class=\"col-md-6\">\r\n");
      out.write("												<div class=\"form-floating mb-3 mb-md-0\">\r\n");
      out.write("													<input name=\"passwd\" class=\"form-control\"\r\n");
      out.write("														id=\"inputPassword\" type=\"password\"\r\n");
      out.write("														placeholder=\"Create a password\" /> <label\r\n");
      out.write("														for=\"inputPassword\">Password</label>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-md-6\">\r\n");
      out.write("												<div class=\"form-floating mb-3 mb-md-0\">\r\n");
      out.write("													<input name=\"passwd2\" class=\"form-control\"\r\n");
      out.write("														id=\"inputPasswordConfirm\" type=\"password\"\r\n");
      out.write("														placeholder=\"Confirm password\" /> <label\r\n");
      out.write("														for=\"inputPasswordConfirm\">Confirm Password</label>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"mt-4 mb-0\">\r\n");
      out.write("											<div class=\"d-grid\">\r\n");
      out.write("												Create Account</a>\r\n");
      out.write("												<input type=\"submit\" value=\"회원가입\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</form>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-footer text-center py-3\">\r\n");
      out.write("									<div class=\"small\">\r\n");
      out.write("										<a href=\"Login.jsp\">Have an account? Go to login</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</main>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"layoutAuthentication_footer\">\r\n");
      out.write("			<footer class=\"py-4 bg-light mt-auto\">\r\n");
      out.write("				<div class=\"container-fluid px-4\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"d-flex align-items-center justify-content-between small\">\r\n");
      out.write("						<div class=\"text-muted\">Copyright &copy; Your Website 2023</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"#\">Privacy Policy</a> &middot; <a href=\"#\">Terms\r\n");
      out.write("								&amp; Conditions</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</footer>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
